Blog.Web/Controllers/BlogsController.cs
using Blog.Business.Abstract;
using Blog.DataAccess.Concrete;
using Blog.DataAccess.DTO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class BlogsController : Controller
    {
        private readonly IBlogPostManager blogPostManager;
        private readonly IBlogPostLikeManager blogPostLikeManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;

        public BlogsController(IBlogPostManager blogPostManager, IBlogPostLikeManager blogPostLikeManager, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
        {
            this.blogPostManager = blogPostManager;
            this.blogPostLikeManager = blogPostLikeManager;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }


        [HttpGet]
        public async Task<IActionResult> Index(string urlHandle)
        {
            var liked = false;

            var blogPost = await blogPostManager.GetByUrlHandleAsync(urlHandle);

            var blogDetailsViewModel = new BlogDetailsViewModel();

            if (blogPost != null)
            {

                var totalLikes = await blogPostLikeManager.GetTotalLikes(blogPost.Id);

                if (signInManager.IsSignedIn(User))
                {
                    var likesForBlog = await blogPostLikeManager.GetLikesForBlog(blogPost.Id);

                    var userId = userManager.GetUserId(User);

                    if (userId != null)
                    {
                        var likeFromUser = likesForBlog.FirstOrDefault(x => x.UserId == Guid.Parse(userId));
                        liked = likeFromUser != null;

                        
                    }
                }




                blogDetailsViewModel = new BlogDetailsViewModel
                {
                    Id = blogPost.Id,
                    Content = blogPost.Content,
                    PageTitle = blogPost.PageTitle,
                    Author = blogPost.Author,
                    FeaturedImageUrl = blogPost.FeaturedImageUrl,
                    Heading = blogPost.Heading,
                    PublishedDate = blogPost.PublishedDate,
                    ShortDescription = blogPost.ShortDescription,
                    UrlHandle = blogPost.UrlHandle,
                    Visible = blogPost.Visible,
                    Tags = blogPost.Tags,
                    TotalLikes = totalLikes,
                    Liked = liked
                };
            }

            return View(blogDetailsViewModel);
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using Blog.Business.Abstract;
using Blog.DataAccess.Concrete;
using Blog.DataAccess.DTO;
using Blog.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogPostManager blogPostManager;
        private readonly ITagManager tagManager;

        public HomeController(ILogger<HomeController> logger, IBlogPostManager blogPostManager, ITagManager tagManager)
        {
            _logger = logger;
            this.blogPostManager = blogPostManager;
            this.tagManager = tagManager;
        }

        public async Task<IActionResult> Index()
        {
            // getting all blogs
            var blogPosts = await blogPostManager.GetAllBlogPostAsync();

            // getting all tags
            var tags = await tagManager.GetAllTagAsync();

            var model = new HomeViewModel
            {
                BlogPosts = blogPosts,
                Tags = tags,
                
                
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Blog.Web/Views/Home/Index.cshtml
@model Blog.DataAccess.DTO.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-xxl-9 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-12 col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">Wissen Haber - Haberin merkezi</h1>
            <p class="lead">Dünyanın her yerinden güncel haberler ve özel blog yazıları için bizi takipte kalın !</p>
        </div>

        <div class="col-12 col-lg-6">
            <img src="https://images.pexels.com/photos/6262966/pexels-photo-6262966.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Bloggie - Dev Blogs" class="d-block mx-lg-auto img-fluid" width="300" />
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 d-flex">
            @if (Model != null && Model.Tags.Any())
            {
                foreach (var tag in Model.Tags)
                {
                    <span class="badge bg-dark me-1">@tag.Name</span>
                }
            }
        </div>
    </div>
</div>





<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            @if (Model != null && Model.BlogPosts.Any())
            {

                foreach (var blogPost in Model.BlogPosts)
                {
                    if (blogPost.Visible==true)
                    {
                        <div class="mb-5 bg-light box-shadow p-3">
                            <img src="@blogPost.FeaturedImageUrl" alt="@blogPost.Heading" class="mb-2 d-block img-fluid" />
                            <h2 class="mb-4">@blogPost.Heading</h2>
                            <p class="mb-4">
                                Author : @blogPost.Author
                                <br />
                                Published Date : @blogPost.PublishedDate.ToShortDateString()
                            </p>
                            <p class="mb-4">
                                @blogPost.ShortDescription
                            </p>
                            <p class="mb-4">
                                @foreach (var tag in blogPost.Tags)
                                {
                                    <span class="badge bg-secondary me-1">@tag.Name</span>
                                }
                            </p>
                            <a class="btn btn-dark" asp-area="" asp-controller="Blogs" asp-action="Index" asp-route-urlHandle="@blogPost.UrlHandle">
                                Read More
                            </a>
                        </div>
                    }
                    
                }
            }
        </div>
    </div>
</div>